- project:
    name: x/networking-cisco
    templates:
      - openstack-python3-jobs
    check:
      jobs:
        - openstack-tox-pep8:
            nodeset: ubuntu-focal
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2023.2
        - openstack-tox-py38:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2023.2
            voting: false
        - openstack-tox-py39:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2023.2
            voting: false
        - openstack-tox-py310:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2023.2
            voting: false
        - openstack-tox-py310:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2024.1
            voting: false
        - openstack-tox-py311:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2023.2
            voting: false
        - openstack-tox-py312:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2023.2
            voting: false
    gate:
      jobs:
        - openstack-tox-pep8:
            nodeset: ubuntu-focal
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2023.2
        - openstack-tox-py38:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2023.2
            voting: false
        - openstack-tox-py39:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2023.2
            voting: false
        - openstack-tox-py310:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2023.2
            voting: false
        - openstack-tox-py310:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2024.1
            voting: false
        - openstack-tox-py311:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2023.2
            voting: false
        - openstack-tox-py312:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2023.2
            voting: false
