- job:
    name: networking-cisco-coverage
    parent: openstack-tox-cover
    description: "Runs unit tests with coverage reporting."
    vars:
      tox_envlist: cover

- project:
    name: x/networking-cisco
    templates:
      - openstack-python3-jobs
    check:
      jobs:
        - openstack-tox-pep8:
            nodeset: ubuntu-jammy
            required-projects:
              - name: openstack/requirements
                override-checkout: unmaintained/2024.1
        - openstack-tox-py38:
            required-projects:
              - name: openstack/requirements
                override-checkout: unmaintained/2024.1
        - openstack-tox-py39:
            required-projects:
              - name: openstack/requirements
                override-checkout: unmaintained/2024.1
        - openstack-tox-py310:
            required-projects:
              - name: openstack/requirements
                override-checkout: unmaintained/2024.1
        - openstack-tox-py311:
            required-projects:
              - name: openstack/requirements
                override-checkout: unmaintained/2024.1
        - openstack-tox-py312:
            required-projects:
              - name: openstack/requirements
                override-checkout: unmaintained/2024.1
        - networking-cisco-coverage:
            nodeset: ubuntu-jammy
            timeout: 6000
            required-projects:
              - name: openstack/requirements
                override-checkout: unmaintained/2024.1
    gate:
      jobs:
        - openstack-tox-pep8:
            nodeset: ubuntu-jammy
            required-projects:
              - name: openstack/requirements
                override-checkout: unmaintained/2024.1
        - openstack-tox-py38:
            required-projects:
              - name: openstack/requirements
                override-checkout: unmaintained/2024.1
        - openstack-tox-py39:
            required-projects:
              - name: openstack/requirements
                override-checkout: unmaintained/2024.1
        - openstack-tox-py310:
            required-projects:
              - name: openstack/requirements
                override-checkout: unmaintained/2024.1
        - openstack-tox-py311:
            required-projects:
              - name: openstack/requirements
                override-checkout: unmaintained/2024.1
        - openstack-tox-py312:
            required-projects:
              - name: openstack/requirements
                override-checkout: unmaintained/2024.1
        - networking-cisco-coverage:
            nodeset: ubuntu-jammy
            timeout: 6000
            required-projects:
              - name: openstack/requirements
                override-checkout: unmaintained/2024.1
