- job:
    name: networking-cisco-ndfc-tests
    parent: openstack-tox-py310
    description: "Runs only the NDFC driver unit tests as a voting gate."
    vars:
      tox_envlist: ndfc

- project:
    name: x/networking-cisco
    templates:
      - openstack-python3-jobs
    check:
      jobs:
        - openstack-tox-pep8:
            nodeset: ubuntu-jammy
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2025.1
        - networking-cisco-ndfc-tests:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2025.1
        - openstack-tox-py39:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2025.1
            voting: false
        - openstack-tox-py310:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2025.1
            voting: false
        - openstack-tox-py312:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2025.1
            voting: false
        - openstack-tox-py313:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2025.1
            voting: false
    gate:
      jobs:
        - openstack-tox-pep8:
            nodeset: ubuntu-jammy
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2025.1
        - networking-cisco-ndfc-tests:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2025.1
        - openstack-tox-py39:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2025.1
            voting: false
        - openstack-tox-py310:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2025.1
            voting: false
        - openstack-tox-py312:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2025.1
            voting: false
        - openstack-tox-py313:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2025.1
            voting: false
